
trigger:
- none

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerconnection'
    repository: 'pavithra/webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'sc-azsub1'
    appName: 'appservicepractice'
    deployToSlotOrASE: true
    resourceGroupName: 'apkk'
    slotName: 'appservicestaging'