variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'appreg-apkk-dev-uks-01'
    appType: 'webAppLinux'
    appName: 'asapkkdev'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'