
trigger:
- none

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerconnection'
    repository: 'pavithra/webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'