
trigger:
- none

pool:
  vmImage: ubuntu-latest

variables: 
  ## Add this under variables section in the pipeline
  containerRegistry: 'Azureregistrypractice'
  imageRepository: 'pavithra/webapp'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerconnection'
    repository: 'pavithra/webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
       $(tag)
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'sc-azsub1'
    appName: 'appservicepractice'
    deployToSlotOrASE: true
    resourceGroupName: 'apkk'
    slotName: 'appservicestaging'
    containers: $(containerRegistry)/$(imageRepository):$(tag)